### ISSUE TITLE
去除文章页面正文右侧滚动条

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollege.github.io#1]
等待高手，我等菜鸟让路。

**Comment by tsai1993** [comment]
通过将 `hux-blog-mini.css` 里的 `article{overflow-x:hidden} ` 改为 `article{overflow-x:visible}` 解决此 bug。但是这种解决方案使得 `catalog: true` 失效。目前的解决办法是停用 `catalog: true`。

**Comment by cmmei** [comment]
overflow-x 不是控制横向 滚动条吗？

**Comment by tsai1993** [comment]
反正问题解决了……
