### ISSUE TITLE
使用 js 自动在中西文之间添加空格

### ISSUE THREAD

**Issue by cmmei** [LirenCollege/LirenCollege.github.io#16]
参考 1: [pangu js](https://github.com/vinta/pangu.js) ,
 [https://github.com/vinta/pangu.js/tree/master/dist/browser](https://github.com/vinta/pangu.js/tree/master/dist/browser)
参考 2: [https://github.com/zizhengwu/daft-auto-spacing](https://github.com/zizhengwu/daft-auto-spacing)

**Comment by tsai1993** [comment]
这不是用户端显示的问题么，跟我们网站排版没啥关系吧。

**Comment by cmmei** [comment]
排版的时候没手动输入空格，不会显示的。

**Comment by cmmei** [comment]
像这里说的用在博客上用 javascript 脚本，http://kaedea.com/2016/06/26/front-auto-space/

**Comment by tsai1993** [comment]
我试了一下，基本没啥问题，但是省略号会出现奇怪的问题，会在省略号后面自动加一个空格。还有就是 markdown 加粗语法没有正常解析。
![screen shot 2018-01-08 at 00 44 47](https://user-images.githubusercontent.com/7903661/34651589-2d233440-f40d-11e7-8832-f0d261dc623d.png)

**Comment by tsai1993** [comment]
我是用的 atom 编辑器，所以我装了 pangu 的 atom 插件。https://atom.io/packages/pangu

**Comment by cmmei** [comment]
atom 插件似乎不是新版本，我用 js 加载到单独的本地网页文件内，浏览器打开是正常的。
