### ISSUE TITLE
使用 https

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollege.github.io#18]
立大博客现在第一次打开会提示证书安全问题，用户选择信任后才能正常访问，是否可以直接使用 https。

[自定义Github Pages域名并https化](https://himike.win/2017/01/06/%E8%87%AA%E5%AE%9A%E4%B9%89Github-Pages%E5%9F%9F%E5%90%8D%E5%B9%B6https%E5%8C%96/)

**Comment by cmmei** [comment]
之前是用的 cloudflare CDN 解析，今天勿操作改成了 name 家默认的。我再改回去。
