### ISSUE TITLE
背景图片的两个问题

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollege.github.io#3]
1.  感觉背景图片太多太杂了，并不美观。个人觉得可以适当选择一定数量的背景图片，这样既不重复单调又不失水准。（要是能把像刘嘎吱这样的专业人士请来帮忙就好了）

2. 适当压缩图片大小。不然加载速度太慢。

@cmmei

**Comment by cmmei** [comment]
那就让条嘎吱挑一些背景图。
