### ISSUE TITLE
文章左右对齐

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollege.github.io#4]
可以使用`text-align:justify;`使得文章分散对齐。

但是还不知道具体怎么弄。

**Comment by cmmei** [comment]
https://github.com/webcoding/cnBootstrap/blob/master/cnDocs/solutions/text-align-justify.html
这样？

2016年7月16日 12:24，"tsai1993" <notifications@github.com>写道：

**Comment by tsai1993** [comment]
https://github.com/Huxpro/huxpro.github.io/issues/95#issuecomment-236944486
