### ISSUE TITLE
多人反映时常无法打开网站

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollege.github.io#5]
不知道是网站太大还是有其他问题，加载不稳定，并且在微信中显示异常。

另外有人反映电子版下载困难。

**Comment by cmmei** [comment]
网站可能是因为没有添加D N S国内解析，我有空添加一下。
微信中显示异常是正常的，因为没有通过翻墙，而是直接访问，而腾讯对一部分域名识别会出错。
电子版我已经压缩成8M的P D F（原来12M），很多人下载苦难是因为直接访问 github 网站本身不行。

综合起来，如果对 需要翻墙 还感到很奇怪，那没办法。我们又何必在国外注册域名，而不是注册国内的进行备案呢？

**Comment by tsai1993** [comment]
关键是没油被墙，只是访问极其不稳定。看来除了加DNS就是鼓励大家翻墙了。看看有啥好的翻墙教程……永远挂在第一篇。
